# Generated by Django 5.1.1 on 2025-02-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valetcars',
            name='guestID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='valetcars',
            name='ticketNum',
            field=models.IntegerField(),
        ),
    ]
