# Generated by Django 5.1.1 on 2025-02-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_valetcars_guestid_alter_valetcars_ticketnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valetcars',
            name='guestID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
