# Generated by Django 5.1.1 on 2025-02-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_valetcars_guestid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valetcars',
            name='guestID',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
