# Generated by Django 5.1.1 on 2025-02-05 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_valetcars_guestid'),
    ]

    operations = [
        migrations.AddField(
            model_name='valetcars',
            name='roomNum',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(400), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
